version: '3.8'

services:
  frontend:
    container_name: zenlist-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8127:8081"
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.197
    volumes:
      - .:/app
      - /app/node_modules 
    networks:
      - zenlist-network
    stdin_open: true
    tty: true
    # הפקודה המעודכנת ללא הדגלים שגרמו לקריסה
    command: npx expo start --web

networks:
  zenlist-network:
    external: true # מגדיר לדוקר להשתמש ברשת הקיימת שה-backend יצר