version: '3.8'

services:
  frontend:
    container_name: zenlist-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8127:8081"
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.197
      # מבטל את הרינדור הסטטי (SSR) שגורם לשגיאות ב-Logs ששלחת
      - EXPO_USE_STATIC=false
      # מגדיר ל-Expo לעבוד במצב לא אינטראקטיבי בתוך Docker
      - CI=1 
    volumes:
      - .:/app
      - /app/node_modules 
    networks:
      - zenlist-network
    stdin_open: true
    tty: true
    # הוספת --non-interactive כדי למנוע מהשרת לחכות לקלט משתמש בטרמינל
    command: npx expo start --web --non-interactive

networks:
  zenlist-network:
    external: true